# Generated by Django 4.1.2 on 2022-10-17 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('description', models.TextField(blank=True, max_length=2000, null=True, verbose_name='descrição')),
                ('hour_value', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='valor_hora')),
                ('picture', models.URLField(verbose_name='foto')),
            ],
        ),
    ]
