# Generated by Django 4.1.2 on 2022-10-23 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_classroom'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together={('email', 'teacher')},
        ),
    ]
