# Generated by Django 4.1.2 on 2022-11-01 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_alter_classroom_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teacher',
            unique_together={('name', 'description')},
        ),
    ]
